export const ANNOUNCE_CREATE_REQUEST = 'ANNOUNCE_CREATE_REQUEST'
export const ANNOUNCE_CREATE_SUCCESS = 'ANNOUNCE_CREATE_SUCCESS'
export const ANNOUNCE_CREATE_FAIL = 'ANNOUNCE_CREATE_FAIL'
export const ANNOUNCE_CREATE_RESET = 'ANNOUNCE_CREATE_RESET'

export const ANNOUNCE_LIST_REQUEST = 'ANNOUNCE_LIST_REQUEST'
export const ANNOUNCE_LIST_SUCCESS = 'ANNOUNCE_LIST_SUCCESS'
export const ANNOUNCE_LIST_FAIL = 'ANNOUNCE_LIST_FAIL'

export const ANNOUNCE_DETAILS_REQUEST = 'ANNOUNCE_DETAILS_REQUEST'
export const ANNOUNCE_DETAILS_SUCCESS = 'ANNOUNCE_DETAILS_SUCCESS'
export const ANNOUNCE_DETAILS_FAIL = 'ANNOUNCE_DETAILS_FAIL'

export const ANNOUNCE_DELETE_REQUEST = 'ANNOUNCE_DELETE_REQUEST'
export const ANNOUNCE_DELETE_SUCCESS = 'ANNOUNCE_DELETE_SUCCESS'
export const ANNOUNCE_DELETE_FAIL = 'ANNOUNCE_DELETE_FAIL'

export const ANNOUNCE_UPDATE_REQUEST = 'ANNOUNCE_UPDATE_REQUEST'
export const ANNOUNCE_UPDATE_SUCCESS = 'ANNOUNCE_UPDATE_SUCCESS'
export const ANNOUNCE_UPDATE_FAIL = 'ANNOUNCE_UPDATE_FAIL'
export const ANNOUNCE_UPDATE_RESET = 'ANNOUNCE_UPDATE_RESET'
