export const SEARCH_LIST_REQUEST = 'SEARCH_LIST_REQUEST'
export const SEARCH_LIST_SUCCESS = 'SEARCH_LIST_SUCCESS'
export const SEARCH_LIST_FAIL = 'SEARCH_LIST_FAIL'

export const FILTERED_LIST_REQUEST = 'FILTERED_LIST_REQUEST'
export const FILTERED_LIST_SUCCESS = 'FILTERED_LIST_SUCCESS'
export const FILTERED_LIST_FAIL = 'FILTERED_LIST_FAIL'
